(dataset)LeaveOneOut:
  class: LeaveOneOut
  in: (in_task)->out
  group_col: !var (dataset)_leaveoneout_group
  cache: False
(dataset)KFold:
  class: TaskGraph
  cache: False
  in:
    data: (in_task)->out
    labels: (dataset)LabelEncode->labels
    dev_partitions: !map (dataset)LeaveOneOut->train
    test_partitions: !map (dataset)LeaveOneOut->test
    data_processor: (dataset)DataProcessor->out
  outputs:
    predictions: (dataset)PredictionIndex->out
    targets: (dataset)TargetIndex->out
    metrics: (dataset)Metrics->out
  Tasks:
    (dataset)PartitionDevTest:
      class: Split
      in: self->data
      split_col: !var (dataset)_leaveoneout_group
      group_outputs:
        dev: self->dev_partitions
        test: self->test_partitions
      in_memory: !nocache True
      cache: False
    (dataset)Partition:
      class: OutputMerger
      cache: False
      in_memory: True
      outputs:
        train: (dataset)PartitionDevTest->dev
        validation: (dataset)PartitionDevTest->test
    include:
    - config: ../model/model.yaml
      suffix: !var dataset
    #include:
    #- config: ../features/normalize.yaml
    #  dataset: (dataset)
    #  in_task: (dataset)Partition
    #  model_mods: (dataset)Metrics/labels=self->labels&(dataset)TrainGenerator/batch_task=self->data_processor&(dataset)ValidationGenerator/batch_task=self->data_processor&(dataset)TestGenerator/batch_task=self->data_processor
#(dataset)MergePredictions:
#  class: Concatenate
#  in: (dataset)KFold->predictions
#  axis: 0
#(dataset)MergeTargets:
#  class: Concatenate
#  in: (dataset)KFold->targets
#  axis: 0
#(dataset)MergedMetrics:
#  class: ClassificationMetrics
#  predictions: (dataset)MergePredictions->out
#  targets: (dataset)MergeTargets->out
#  export: True