defaults:
  temp_dataset_paths: !nocache ['~/temp/1','~/temp/2']
  zips_per_batch: !nocache 40
  zips_path: ~/Datasets/audioset_wav
  zip_glob_expression: /*_train*.zip #Balanced + unbalanced
ListZips:
  class: GlobWrapper
  parent_dir: !var zips_path
  expression: !var zip_glob_expression
  in_memory: !nocache True
GroupZips:
  class: Group
  n: !var zips_per_batch
  in: ListZips->out
  repetitions: !var n_epochs
  shuffle_repetitions: True
  in_memory: !nocache True
DestinationPath:
  class: CycleList
  out_shape: GroupZips->out
  cycle: !var temp_dataset_paths
  in_memory: !nocache True
BatchedTrain:
  async: True
  return_as_class: True
  class: TaskGraph
  in_memory: True
  cache: False
  in:
    train_zips: !map GroupZips->out
    destination_dir: !map DestinationPath->out
  outputs:
    frames: AudiosetBalancedSamplingMixup->out
  Tasks:
    RemoveWavs:
      class: RemoveFiles
      folder: self->destination_dir
      in_memory: True
      cache: False
    CopyZips:
      class: CopyFiles
      run_after: RemoveWavs->out
      source_files: self->train_zips
      destination_folder: self->destination_dir
      in_memory: True
      cache: False
    ExtractZip:
      class: ZipExtractor
      destination_path: self->destination_dir
      in: CopyZips->copied_files
      in_memory: True
      cache: False
    include:
    - config: ../datasets/datasets.yaml
      in_task: ConvertToWav->out

    
