global:
  dataset: balanced_audioset
  features: none
  AudiosetBalanced_data_processing_task: AudiosetBalancedDataProcessor->out
  AudiosetBalanced_data_generating_task: null
  AudiosetBalanced_training_data: BalancedFramer->out
  AudiosetBalanced_validation_data: EvaluationFramer->out
  dienen_config: !yaml configs/model/architectures/audio_spectrogram_transformer.yaml
  frame_size: 158960
  hop_size: 158960
  Audioset_partition: random_split
  batch_x: audio
  batch_y: events
  model: dienen_model
  audioset_path: self->destination_dir
  batch_size: 64
  n_epochs: 30
  #steps_per_epoch: 25875
  sr: 16000
  wandb_run_model: WANDBExperiment->out
  experiment_name: vit-pretrain-audioset-events
  swa: False
modules:
- tasks
cluster_config:
  manager: ray
Tasks:
  include:
  - config: ../model/model.yaml
    suffix: AudiosetBalanced
  - config: ../batch/event_classification_batch.yaml
    dataset: AudiosetBalanced
  - config: ../datasets/datasets.yaml
  WANDBExperiment:
    class: WANDBExperiment
    project_name: vit-pe-balanced-set
    experiment_name: !var experiment_name
    run_first: !nocache True
    cache: False
  EvaluationAudiosetReader:
    class: AudioDatasetFromDirectory
    run_parallel: True
    dataset_path: ~/Datasets/Audioset/evaluation_set
    parents_as_columns: #Use parent folders names as these columns
    - partition
    stem_as_column: youtube_id #Use filename as this column
    metadata_files:
      EvaluationSet:
        path: ~/Datasets/Audioset/eval_segments.csv
        read_csv_kwargs: !var read_csv_kwargs
        merge_column_self: !var merge_column_self
        merge_column_others: !var merge_column_others
  EvaluationOntologyDecoder:
    class: AudiosetDecodeOntology
    in: EvaluationAudiosetReader->out
    audioset_path: ~/Datasets/Audioset
    ontology_file: ~/Datasets/Audioset/ontology.json
    column: positive_labels
    new_column: humanfriendly_labels
    in_memory: True
    cache: False
  EvaluationMultiHotVector:
    class: MultiHotVector
    in: EvaluationOntologyDecoder->out
    class_map: ~/Datasets/Audioset/audioset_class_map.csv
    column_out: labels
    column_in: positive_labels
    class_map_key_column: mid
    class_map_index_column: index
    cache: False
  EvaluationFramer:
    class: Framer
    in: EvaluationMultiHotVector->out
    time_column: samples_count
    frame_size: !var frame_size
    window_short_audios: True
    hop_size: !var hop_size
    run_parallel: True

